runtime: python312
handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /.well-known/webfinger
    static_files: .well-known/webfinger
    upload: .well-known/webfinger
    http_headers:
      content-type: application/jrd+json

  - url: /.well-known/keybase.txt
    static_files: .well-known/keybase.txt
    upload: .well-known/keybase.txt

  - url: /(.*)
    static_files: \1
    upload: (.*)
